name: Deployment auf den EC2 Maschinen des LBs

on: push

jobs:
    SSH-setup:
        runs-on: ubuntu-latest
        steps:

            - name: checkout
              uses: actions/checkout@v5

            - name: ssh setup
              run: | 
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/meinPrivateKey
                chmod 400 ~/.ssh/meinPrivateKey
                ssh-keyscan -H ${{secrets.EC2_IP1}}  >> ~/.ssh/known_hosts  
                ssh-keyscan -H ${{secrets.EC2_IP2}}  >> ~/.ssh/known_hosts  
                ssh-keyscan -H ${{secrets.EC2_IP3}}  >> ~/.ssh/known_hosts  

            - name: index.html für nginx bereitstellen
              run: |
                scp -i ~/.ssh/meinPrivateKey frontend/index.html ubuntu@${{secrets.EC2_IP1}}:/home/ubuntu/index.html
                ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP1}} "sudo cp /home/ubuntu/index.html /var/www/html/index.html"
                scp -i ~/.ssh/meinPrivateKey frontend/index.html ubuntu@${{secrets.EC2_IP2}}:/home/ubuntu/index.html
                ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP2}} "sudo cp /home/ubuntu/index.html /var/www/html/index.html"
                scp -i ~/.ssh/meinPrivateKey frontend/index.html ubuntu@${{secrets.EC2_IP3}}:/home/ubuntu/index.html
                ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP3}} "sudo cp /home/ubuntu/index.html /var/www/html/index.html"